# Generated by Django 5.1.4 on 2024-12-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments_service", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="description",
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
