# Generated by Django 5.1.4 on 2024-12-26 12:22

import user_service.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/",
                validators=[user_service.validators.validate_file_size],
            ),
        ),
    ]
