# Generated by Django 5.1.4 on 2024-12-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_already_activated",
            field=models.BooleanField(default=False),
        ),
    ]
