# Generated by Django 5.1.4 on 2024-12-27 07:48

import django.db.models.deletion
import user_service.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0003_user_is_already_activated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="peers",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/",
                        validators=[user_service.validators.validate_file_size],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
