# Generated by Django 5.1.4 on 2024-12-29 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_service", "0004_avatar_remove_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="avatar",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
